# Generated by Django 6.0.6 on 2026-06-13 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewing", "Reviewing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        default=list,
                        help_text="Parsed CSV rows stored as JSON for review before commit",
                    ),
                ),
                ("total_rows", models.IntegerField(default=0)),
                ("imported_rows", models.IntegerField(default=0)),
                ("skipped_rows", models.IntegerField(default=0)),
                ("anomalies_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_sessions",
                        to="groups.group",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportAnomaly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row_number",
                    models.IntegerField(help_text="1-indexed row number from CSV"),
                ),
                (
                    "field",
                    models.CharField(
                        help_text="Which CSV field has the issue", max_length=50
                    ),
                ),
                (
                    "anomaly_type",
                    models.CharField(
                        choices=[
                            ("duplicate", "Duplicate Entry"),
                            ("format_amount", "Amount Format Error"),
                            ("format_date", "Date Format Error"),
                            ("name_case", "Name Casing Issue"),
                            ("name_variant", "Name Variant"),
                            ("missing_payer", "Missing Payer"),
                            ("missing_currency", "Missing Currency"),
                            ("settlement_as_expense", "Settlement Logged as Expense"),
                            ("percentage_sum", "Percentage Sum Error"),
                            ("negative_amount", "Negative Amount (Refund)"),
                            ("zero_amount", "Zero Amount"),
                            ("non_member", "Non-Member Participant"),
                            ("departed_member", "Departed Member Included"),
                            ("date_ambiguous", "Ambiguous Date"),
                            ("conflicting_split", "Conflicting Split Info"),
                            ("duplicate_conflict", "Duplicate with Different Values"),
                            ("decimal_precision", "Excessive Decimal Precision"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "original_value",
                    models.TextField(help_text="The original value from CSV"),
                ),
                (
                    "corrected_value",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Suggested or auto-applied correction",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "auto_resolved",
                    models.BooleanField(
                        default=False,
                        help_text="True if the system auto-fixed this (e.g., comma removal)",
                    ),
                ),
                (
                    "user_action",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("auto_fixed", "Auto Fixed"),
                            ("user_approved", "User Approved"),
                            ("user_modified", "User Modified"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable description of the anomaly"
                    ),
                ),
                (
                    "ai_description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="AI-generated enhanced description (Gemini)",
                    ),
                ),
                (
                    "related_row",
                    models.IntegerField(
                        blank=True,
                        help_text="Related row number for duplicates/conflicts",
                        null=True,
                    ),
                ),
                (
                    "import_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="importer.importsession",
                    ),
                ),
            ],
            options={
                "ordering": ["row_number", "severity"],
            },
        ),
    ]
